[package]
name = "command"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "command"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.32.1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync"] }
async-process = "2.2.0"